---
language: python

python:
 - "3.7"
 - "3.8"

install:
 - pip3 install -U pytest pytest-pylint pytest-doctestplus requests
   requests_mock pytest-mypy inotify_simple blinker

script:
 - pytest -v --mypy tests
 - pytest -v --mypy --pylint --doctest-rst prusa/connect/printer

before_deploy:
 - python3 setup.py sdist
 - python3 setup.py bdist_wheel
