---
language: python

python:
 - "3.8"
 - "3.9"

install:
 - pip3 install -U types-pkg_resources types-requests
 - pip3 install -U pytest pytest-pylint pytest-doctestplus requests
   requests_mock pytest-mypy inotify_simple func-timeout responses

before_script:
 - export TZ=Europe/Prague

script:
 - pytest -v --mypy tests --log-cli-level=10
 - pytest -v --mypy --pylint --doctest-rst prusa/connect/printer
 - pytest -v --doctest-plus prusa

before_deploy:
 - python3 setup.py sdist
 - python3 setup.py bdist_wheel
