; generated by PrusaSlicer 2.1.1+linux64 on 2020-02-11 at 12:00:44 UTC


;
; thumbnail begin 16x16 608
; iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABjUlEQVR4AbWQTUsCURSGZ2Wr3AVpVp
; YGIWJ+po7OOOM44zh+jSRJoOVHSkSLolW7fkAE0a5F7ou20S7oj/hT3jw3EKGyGmjg3MvMfZ/nzD0c
; 9x/P4vycuxNzXVIVNhfa9B502iXaZ0IUvsh6hm/HCXxXJPpScFP1vc4Cp4v+7FP338LTxWCyWYEfWq
; ERE5wK7qEVwWQe46X90o9ZEtDAOZvNZun+j60QHPY5iYvH47jaifwJfj6MoZncQCQSGXGiKEIVefRT
; Hjzth3+Ge1Fc17agCDzS6TSYQJZllFQZZ6Ibw0YA97sB3NX9NOlJx1vTh962C+3EOnRFgiRJEAQBHC
; 0kyOfzMA0N3ZgLzbATg8QyzjNrOEmtojsGD6JL6Ke9KOsqyxIzEZBNVVUUi0U0qkV0eQ+OkitMthd0
; sL3Le1GvGDAMg2VJkMlkPgR0jWw2y8ylUgm1Wg0dncdA9qMlh9DSEjBNk51RhrLE5HI5cNSdimyKok
; DTNNalXC4zqFKpMJC+0RnBlC0UCtB1He91MLXiB9IHtQAAAABJRU5ErkJggg==
; thumbnail end
;

;
; thumbnail begin 220x124 11680
; iVBORw0KGgoAAAANSUhEUgAAANwAAAB8CAYAAAACRt5vAAAh/0lEQVR4Ae2d+XMU17XHVRVnK8dOYs
; BmR4h9FyABEtpBLAKxb9pgEIsQYLABY4xZjbfEy7PjeHneKMcVO7bj91zlGDt5lSJxJb/lL/Av/Cn3
; 9ed0n1ar1TPTs0oj3VN1araeme57z/d+zz3n3NtlZVasWLEylmTiAz8t3zx/QkK1zIoVK4WRyskPNn
; 3es/ze9yfXmKC+vn3h3cPVU2+UWbFiJXeB1QBUGGhRCiA5FnCWWbFiJb5kAjQLPitWchDAhquYLdii
; wGddTytWQpIrq2XKfvxfJueGwpioBm74HfSpllm3UYCN8h+oDe5YGZGCYUYFRYoFvmSAycd/WLfWyo
; gRWANDLzbQiq0WdFaGVYrlPo4UhS0zcWGtWMmbYHjD4T6OBNCVWbFSDNGAw1hitShlflhmxUq+RIFF
; EESDEGORzVKpTU9YyViigFVKRj/catMFVoaI5p4052SBlV+1kUsrImMtgmhBZ2VYBTYrJaMtZbWRSy
; tl1m0srtrI5RgW3MlSMlYLOislLdadHD4lKFVmZWyJdSeHV7WYuszK6BfrTo4szXQJkZUSE0LUpWSQ
; Y0Ut641Sse5kaQDPst4oEOtOlh74bHlYCYt1J0sXeNbdLEGx7uToAJ51N0tArDs5+sBnazRHsFh3cv
; SpTaKPYBkLm/iMNbVF0SNUrDs5OtXWZo5AGaub+YwFvbxulgXcSBILttGtNlUwgsSu5h792jZ/wo0y
; K8MrduuEsaP1Mx9KlFkZPsn3HWmsjmyd9OBPm8qsDI/Y+drY0jtHqy3ghkusCzn29Iue5eaBn95XXm
; aleGLna2MbcGVWiidj5RZQVqP1hbZ5tsqkWGLna1ZftIArjtgdt6yiR1dNs1UmhRZb8W9VdX/lJLtS
; oNBi2c2qatXUX94os1J4+SqxsqQMw2ph1O51UiQ5UzfjbikZhtXCqd1qoQiydNIDiU+6KkvKMKwWRu
; 2K7yLJ0+tmlZRhWC2c2n1NiiAHq6bc/f2OhSVlGFYLo3abhSLIsskPJJ5qqTD/c2hFSRmH1cKoXYha
; BLniuJW/3TKvpAzDauHUBlAKLE608t5lB3QfdywrKcOwWhi1AZQCizNZTlxdP9uca5hZUoZhtXBqAy
; gFlmutsw1zuVfbF5SUYVgtjNoASoHl8Ybye7DchcaZ5ouDy0vKOKwWRm0ApYCyfMqDiRsbXJa7tXFO
; SRmG1cKpDaAUUJ5xgHZl/SxhuY8OLC0pw7BaGLU7MhdQzjXOvHfdm8s92VxRUoZhtXBqAygFEtzKm8
; Jysw1BlFIyCquFUwu4Aspzm+Ya5nIvbZ1fUkZhtTBqt18osBCtvLlhjnl716KSMgyr+dVvj1ab3+9c
; ZCbb/SoLKyunPpiA5WzQZGyD7VxDuWlf+LANmBRDnt88l8RnSRmJ1fzoHQ9sncsn37O7MRdJjq2edv
; frXrv9wljTN3YsNMfXTDN9jjbPGmfrKYslK6f+MvF/x1eVlLFYzV5hNcDmDLQCONitzErxxN5WeAyB
; 7UiVOVtf7oMNdps34f5EmZXiiQXc2AWbZbciywMPPNC0o3bpvVIyHKuZ6+vbF5reVVMHgQ21aYAiyU
; 9+8pPySZMm3Vi5cqXp31RdUsZjNb7Cagq2ow7YAFyfDZQUVwDbkiVL7gE29PI2C7jRCrbnnJRPb/UA
; 2JTdDq8pN3NnTrOAK7QoqwX1w+7VJWVIVuOB7fTaGS7YhriS0037qvnS93PnzrXJ7kIIrObI7TDYLO
; BGp1LIcNgB25EA2AbYbeag/sfbYS5fZiU/Mm7cuEQU0FS/OmIBN9r0csssAVvYlTxRM9201qwwmzdv
; HmIHDMhlVrKXYGAkmfb19Zmbpw6WlDFZTa24k8nA1lM7x9TV1Zna2lqzadOmIfZg2S5LCQdGwtrQ0G
; COHTtmtm/fbtauXWu2rV1u/nvPYvPdURtAKXXFnfTB5gEOsPXWVJiNa6sEcKr0fZR9MFCXWUkvcVit
; vb3dnDt3zjQ1NUmDa+N31y2UQlbckbd32+U6paovtM0LzdumC+D21y4YBDbVmpoas27duki2w57KrE
; QLjUPUKRnQ6uvrxYXs7OwcBLSgHm2YJ6B7rL7cXGqpMG/ZdXIlpbiTR1cNdSVht6j+DmpjY6Nlu7iS
; jtVozJs3b5rW1takYFM91jDfnG+caR53gHemboY5VTvd/H7nQlk3VUrGNxYVdzKcAgBwW2or0wJO2W
; 7jxo1D7MemDzxJ50LSiLAa87U4DY4219WYE/WzBHQwHfV3gI6O4/lr2+3dd0aqBpfcKNh6aueKdxO3
; /xmQ169fbwMqYUkXGIHVrl69arZs2ZKW1VTpGHR9fY0A7kKTAzqH6R51mI5EKh3IhPxR5/l/bVtgvn
; FcmFIyyNGubAgVBNwRx5VscQZQ7de4oNNIJsG1Me9ixg33X7hwQUAXt4G1U1Tb6leZJxzAsW/lOXEv
; ywV0/Q7o6FSqGA5WTREQvudEOEvJMEejfhFyJ+mXXbVLhvRrpqAb0+mDdKymgZG9e/fGZrUosKGMbt
; vqVsielRcdPefN62C7k46LyQhK2VDCAV33isnS0Z/aWxoPmw52J6eZnpo50odRfZsJ6NAophuVbBeH
; zVQJ8z/99NMS4s0EbFGAo4FVO9YulIjlxeaZfjDlbD3BFNfFZFSljKhn5RRRuz/K8Cj3iujzUgG9NT
; PNuvpavw9zBZwGVDZs2DB6Ayrp2CwcGEkkEhkDLR3YUNzS443zBXSw3RNNFXKrKwIqj4ZdTAdwvH/H
; RjSLqrS3shuP7Y5nEu7HfIBu1AZUgqy2ePFiM3v2bEaSSFZ74403zIEDB6RRcwVbGHCATfVUy0LDjR
; zVxRS2q3dTB/3iYk6TkiIe+ayUDLbUlbSNJrr31y70+ywV4LIFHd/bsWOHaWlpGWKPJVmPGS42Bmjj
; x483c+bMGXRxJ06cMM8884yAjUgkdJ9PdguCDWC3NKwV9iISBtsRUPGZjnydF8WE8Xh93W6fXhQlUg
; zQOpZPNgeqZkhfBfsunyynYCNXB+C2bdtW+mwXnrNVVlaaefPmDaqDxIXcvXu3aW5ultdtbW0COBo7
; LtPFZTd+U3VDU51ELQEdbHepOQQ8B3REM2E4Hu2OzvlVKkmYI3+4b4lhP1ECWdsWPWz2LJ1oOh2wrW
; +s8/sq3yxHbICBHZsLf1bSAZVUQRLqIJ944gm56PB8jcYFhICPBs8nu6H8J7qlqUYAxySdustLnot5
; IQC8Jz0gEmD58tCKkjLq4VYYC31v7xLzvqO3Ns3lPtzirssqAO+R+fKBykkSJT60eqbZ3LBG+icMuF
; xZjmOoUNq1a1fSwZyAStTcjoDKiK/HjAKchvu7urpSBkZoEEaiPXv2SCMla9Bs2E0BhyuxvaXW3Gh1
; Qfe0w3QYhICu0Y1kuu85QGxyX1vQDdW/eMB618lhXt8wx9xwlLbqclIsnY57eAggOaqLSI/5e5JMF7
; ARGUYPOmDbuXaZ3z/BPsuV5TieFSVxpyv8Vsm5mGHA0WC3bt2Si44TheSiAQV+NgsNo9guW3bjd1FA
; va9hudx5h1tdqXspARUninnNASI3e5T3W1wG/N/E2AYdAKOtqNw5smqa2bdsktmPOiwFU3Uun+QAab
; KkVnRrBK3276txy7R43eOBLUEqZpUDtrplfr+EQZcLy2E/zNEyDcbBdlHJ8hGZPgiCDXDBamgmFxx0
; Mbdu3SpApTO0YXNlNwUc2lm/WEZmgAeriYvpAIz3rg9iwArDXXpKCSD5UuZdr21fIMUBgMwH2jIFGi
; BzGe1w9eDdtU7UTJMgFIUGfHbIAVvCY75uB2x76iulH5IBLhuW4zvYTSoPKZ1SocL3RyzbhRPcNMq1
; a9fkwrPJrQWZDN+6p6dHRqyoxs6G3VB+V367dp6Ai9H7igMuAMbtjLnZo+92OmzHZ6+0j6370H3mBD
; gohwMkuIqDGW2yuIaAR7exY8GoRnoVaH01AzlOjqWcrmtVuTAb7a/9kSvLoRoY4Xeztbkw8EZcQAXE
; BxPcMNqTTz6ZUR1kOtDxW7iXuAh0Qj7YTQHHSJaomy+Au9rqupLPOhG0Z53JPsCD7eQzz8V8eQyATv
; eDTHisBWBgOEL3PAKcRGB+dtyr7AdgpFcAKRFfnnOsVvGgLtgq/fZPB7g4LMdrBuSdO3dmlc9N52JG
; 5eyKvsA1zGoaGNm/f39OrJZMNaBCFBOQ0AHpABcHbChu6+H6+cJmsB0h6+cDoLvpge6aB0jC2vk28r
; /0Vol+0lVpPukcnppOBZrumNUbiCwqyFy3ceogl5EyOcBF/vJsXbmf24TVAGjPCndu11ldbrY0r/Xb
; PS7oUgGO48mt8f1821x44B82tguXbdEoLKXJpg4y04uWKKMTeWJiy/Nc3EkFG8oIeXDtPAEdy/xfdJ
; TH59tc0F1tnSWpAvJzjOZ8FjZWVSrfP3BAqfpq+wJhSvkd5/cxSFIOGC85qN3oEtVH5D0M/RXne8Uq
; qOa8cacJiOgmPkcD0cXglnXqLiqTnfFAhpJa8fb9F7AJ4Jw5HmBrW9/st3c2gAuCjue4j9iBej2FBJ
; yyXVHrMcOsxknAaocPHy74xSrg1MVkfsh2C3RMFNjSAS7Ibgq4Xa0NEmnDmDAuRnSCBO0LHzab5k8w
; G+eNH6KA40Sgyh2DPCqs4BqpG/6eIqN9zwpGfFelsqLSDT7sdX5j37KJ8ojyPnOmjkpXu5xjn2isEO
; AWAmhU6vt5ssBuWeE9IZXNTgvIZkgR+OMeyDSlwmAE2LpWDACue80s09bqRp6DgFPQZepWcgzfhdmC
; bFcMG4RQkrmYeQ2ohPcc4eJffPFFmVsVktWiAKego1Pw25nbKfCycScxBBQQ79rmaMNKcaEIEOxc/E
; gk0IK62QFjh3MsQNXRH3fruDe/gTXUPUtUe8EDndN4easDXjACAGKkClTC5xLZC0T4MHpcvzs5LqC9
; vX+psNKx1V6ubM0AwIJAI7TPfz7qAU0ZGoDB+qRSzjug4/wUbAq4vWsXS8EDxem0r4IuW7eS71AOyL
; G5lnrlogVd4BrOrcFqjz32WN4nqHHBFpy70Tm4FYCOzsjWneT7VCMwajKI7G1cKfMSDIz5iOz6W+2C
; EFBQkhQG3pYFEyTAwJYOMq+pneEvpgSAfcp+3pKgwwomL7DQvXIgaRxcG9YX2MFKtx4Ql88BMgzz5s
; 5F4sbGZrWj1VJtE9yKbjDABrY4UGVuBsiEzZpmyqoLgKZ1qTJHC4Ftd4O7aSsK6Pbt2+fXMmbqVvKc
; 3+C3gq7lcIMOtzZvbBcV7gdsGGaxWC0d4FA6hGAKHaJzu7iA43hGTIyB31AD4Xl/yyLf8HiErY7J3G
; aq7y72eCVKu5y5F2y41QHdDucx6H6d8pYBaci8z3PXAMxg19MFIL9/2ov2qZ4Kqf++gNudT1Exc2vj
; XPPO7sVJgSYLPQMrq4+HbgGl13pizXT/nFFWzV/wGI0CAXKTRG35X4AmYAsAbo8zYAXbk3bmkWkA9s
; PzuIADoPQtj7mWehXKNnMOqIQDI1ww4X4ao9hgSwc4dSXpMKKkjKJx5m9cE+VmClQ1CgwFZfTqa17k
; 55kUGEGXsNtzCXVO5iaHJwoDYniw4xlPMc6TgTyVGvMxL0Bx1AMzBq9BCNWzgUeCFGfrdB41+Bg+cz
; 8vFwDCfm/uWiRbBiozhtksyGTBPFpQARtAu+SBjeenvIR2T4DVaBPARttpOyrgUPUm+vv7/QR1MsDx
; mkGRPuW9bKtOisV2XGvGAZVkgRGSz8MBtLiAU9BpRzGS0ulBwOloSicyyhLtpJEwgmSA29m2UYwMgw
; ZkJG67Q0Db7wFtrwM0Zbodix6R5x3LJwlAz0rI3AWIy1juXO+kN+frrx0of+K1BiH0ET3X6BZYu+q6
; d+cDz1Upv6KcigGA+eUmx90Vne+6vZyXuq59YaAF5qF6frxWZoPVcCUTVW7a4LCXo0Npn90O2ABSKs
; Cp8hrPgv5Q0Gl/8ZqtNhgMM6k6GU775Lo559guZpjVMq2DHAmAk7VvgVpMgMX5K+DoZIBGsCXc+VGA
; oxH3bW6WShMMW0C30gWdBjkAG9HKXU5YX8Dm6DYnsrl1wcN+ES8hfwx3MBu580N1C096hk9wQhfKXt
; Qaz2Z3m4iLXpBCNkhqqhgETJhNUw3bHcBHzTNVAR/uLxFYGPmgVwPZ7wHtVEB5zf/BmAwWBHCOeIzf
; 6zGc5OlqKqS94gBO58/0Ax4JxyvL8R1WjvA80zKv4bBN7A3G/uCDD8yVK1fMwYMHxcZSLnANLxxlL0
; gWiQ7nqJEt4JTpcFfoUJTOxhC6u7v9+UMwQqlgiwIceqCtRZLi5KoABGBTlttfOZBDgz0EcI6xb104
; QVwtjJFgCUwI42nwQcEHUKQywwu04A7CJJe9UjNqPFFcuUui7sp13TYC8JJyADwAjf/nPLY6rzfPH5
; 82yupGWsfL9132c5fN4Ooq03HOnJumDdz558Dc83DNLLO9bWNSwCnogoBT1573jxw54nsdqLqVIx1w
; XMehQ4fMb37zG/Pxxx+bv/3tb+bNN98U/DBdiWI7Ybbgmy+88II5fvz4sLNaroBTV5JOP336tOno6J
; DOjkoJhAGHwQQBJ/O9reul6oQIHwbI/EfyZcsneW7lRGEXWG67AzhYDmBKvWH1VH+O1uOx5PmAi/h4
; AHi8pqLlqujsQapr+QAa/0/eToHG/+4J5PEADwMBx8DEOs8EUB1ePeQB77y1TpLv4xrzPU1VoBzv10
; N655/wqk64rs51q6SNgoBT0KUDHMpxMAM5XV5nW8hcLHvk3I4ePWpeffVV88knn0iK7J///Kf57LPP
; zB/+8AdZ9wkQeQyDruy+++4bBLjq6mr5MQyUyWCpAg6lIxkxZT7mMB2jTjYMhzEx2e/aVC8VI5R5ae
; BAI3MAD+N23UuXaTBmZQHdM0XzdRg5bKFb+D3muZk8h01VKaLWmk5cS8ALyFD3P1zm1LmU5vaCQARA
; Wumv4fseAY0OBlP9O9Vwfsq4gIp5oMwFvUeYEwbnPw9UlZu9TVXSNmHAxWE4Hukf+gWXn89wMXlvpA
; KOayGuAcj++te/mq+//tq89tpr5p133jHvvfeeuJcEGNlChOOHAA5ZunSpiVo4ev78+aLm2/IFONhN
; 5wJ0LEynyW0MQ/NBceZwQcCh3Q7oWMmsa+lgKmGuFVN88GkgBfC5OTO3JpF8HCF3jBpXkCoVQKmvz3
; pbPFz3QMaqBdxKgA3TYOi7PRbTQIVGS7sCyucCDA+UCjrOR11b/b4urSFBry4jv7nDmwfyfYDa5SXk
; dZcz8pIdDrNpu6QCXNQcjs8Y1Hk/GDShv3T1P++PFMDx+7DWp59+Ksz2+uuvC8i+/PJLYTnSSwRNKH
; NkOrYyyc4HAjgninIjvNEPWlVVJbeHokGHk+0yDZpQ2RAVpaQzeZ+G4ZrSRSmjACcjcnurFDfrKgIC
; CgRVqBtk/uOWcU0WV0xD7xqO16JfAhCwGolkjB4w9EvOy913hUAIDCMgc8DS4bmnQbdOwTYIcF7ktN
; 1jIpnTee6mlo7pEptun+ncnagVrB1BFqxy3UaNZmoZGGCjLbIBHN9jZb+CLRyl1EQ3xyjohhNweh2X
; L182//rXv8wPP/xg3n33XWE5AotMWSAngNiY5E4+gwCH3H///TemT58eeRCGeurUqWGb18UFnLoj2m
; nJ8nBSO+lM0hlhMZBMAYce2LJeopfXvbV0uJo8l1ssVQ/k7GAvvZNPsPwLt00rOHRbdk0toIBDy7wS
; gaqUYB6wJwA6wK7gg8F2Lh6Y17lzs4HFo9Ro6po2N/jjvb/cZTKNWsLcOjjIzmZr3Nybgi1TwPEa15
; 7cWrDaJFnim+ekePhNBV2xAcd5/u53vzPff/+9eeutt8zdu3fN7du3zZ07d8yNGzfEHQZsqVgtEnDI
; j370o/IJEybcZT/J8IHM7Z577rlhSROkA5zO1+JUmuhEHdBhGHQo7kC40iQYOMGYFHRqaIB7b9t6Cd
; XjXrKC4LnNc8UNJD+GQeOeAbbgLbQwXrdyZZqfx8JN3ORFFDfNc3Nn7V7QZQjYBq0xm+zpYADy31oU
; rauzAVNHgNWUzfYtG2A0Qv693vYI7kBR7hcou5UwLth0YFPAafskC5hoeVdvb6+/LWImBcyas+P4Yg
; MO++K8P/roI/OnP/1JgiN//vOfZdAguAgmuO44YBsCuCDbJXMxcdc4gWK6mKkAR4dhANnUUiro1IC0
; ljIV4BR0HIt2bW6QEP1vt8wTZWnPrU1zxM0EIFL54Rit5OMcELQtGLrywAXZBPkMJUHNHIzHNidQAf
; N1rpg82KWsCqjnYh7yazMHXExdj6af62e81h203JIyt4aSAYGVAAwaBIbOeGvbDq2p8MGm7RVkt2SA
; 45FBTZdVZbtERwMsHK9MVyjAcS3ck5DgIc/5b675+vXr5tKlSxL2v3jxotx0Ji7QUgLOS4Q3TZ482U
; SxHWuD8GfjbGlXSNDh4+tK8FxWC0jBsjOv4/doWAwnjlvJsZK83ep8f8089249je496Y5768IAkEb1
; BqKIk/w8XpBxtHIFgKHBfB/zOKKEuIl8potCE+pyejoQFdVVCtO8VdtTBvKCgbVuusbtUa8ShmuQzZ
; OcxPppb9X2QQdsezav8xPVcd1JjiEAEgxS5bJaAMWFC66DyyfY1K5IUXz11Vfm3//+t7iPRB8JmHBO
; EA7ztrguZGzAqYv561//+m4ytmOySIMWg+2CjUtn4WJkuh4uCnAKOk2OkwvCxcSI4riVCjrmhAc3rJ
; FK+sfrg6Cb5AcrdHV0f2AnK4y/17uTz8FAxLHDy6f1equvVQ/JOr2JEgyhWoTfTnh7i2hAQ1cX8HjI
; u0NQb2ARaXDpjZv7c+aRAM1hNHKAPPpM6oBt97YtPtjiuJModoGR6kLRZOvhogIm6VICfAcvSzcLyg
; fgOE9Yi5UwXA+EwnyNKCSsBpsRQCQ6GbU0J46Co7I48vOf/zyRLKBCI509e7YogONCNbKoOzfna8W3
; gk5dTOpHAZGO3OlYTkG3b0urMAPztkfXDtylRyJ7XqRRtyGQgmbvTj59IfBpuL4/oqj4hFf3yO92eq
; xIsp3f5zc45ogk2d2o6aA7iwYKljmOuaXWSWrdqK6E6Fy3Wq5Jry8Ou/Fa2y4q/5aPFd/BVSL8Zy6p
; K62DfPbZZ83LL78shR/ffvutVI+88sorQipc55kzZyT/lg3Q2IG8oqLi3i9+8YsbZXElVUAFtmOnLh
; q4UGzX6K301h28ct2xK1nFiUbTMCpYVN3WOCynoNu9zWHKhkXCdKcDoMO1k6JnBxj9XpHyuYaB2kq9
; aaSCD3AEVw0Ajsf10XsefB9AwaTMFXFh3TV004asBDgZiJi6dZIVfi2mrP2rnSUDRxhsqdhN6k6d9i
; KYoGvXovJvubiTUQETHSSjtjFPp/wOkeqnnnpKSrJgMypFuMnMF198IQMHriMuZNTaNwXTlClT7j3y
; yCNmwYIFkZ9PnDjxHvgpy0YIqMycOTPyz2l0RoF8g063q6ZRs6k4ibvNQrjqROsvAR1GFxU8iXItBX
; SOS7W3eZWbAqib4dciEunToAevT2mxcuBWWnpXH9zSJ70CZtVLgaJmLWwml9fvJcfbpXDaDbzs9JLW
; GiABwLpCgfPhESaWVeqs96ubY3qal8u563UkA1uQ3XiPOTCuOK+TVZfkur1Csugkx+G+6krwODbFdT
; FX47oAFKF/SrHefvttYTfcRw2QxJ2XOV7g7SDQcCEzYrVUbAdqo9hu1apVwnb52FSIxqUTNRwcJx+X
; L5YLRisxvJMnT/oJ8ziupYJuZ/sW079uibiX7qrvaf42c2e8O7Lqejj/vgbeigKU2kndNeyalnxtcB
; 85HuYaSFhP8mspdUvxgTndNH8ZEMuDjq0ZcEcld1ft5AG3tA4BWypXEuVzBiXaJl11Sb7ZLTh/41HK
; 75ygSirQ8fuwMHO1f/zjH1KWRfE0czMq/ulvmA0Q5uJCgo+8gC0oqdIHnCxgyZbttHOCo1a4odOxnH
; ZgLiynoKMzMSo6FAPMBHS7t281p1uXidvWLwtB3QDGOW9vEHc1dYWAAODpEh5cRS3xYjX3lXWzhQn7
; vGCIrmvT1ICmAg4GdkJ26yPdpUB6TzzKzDQCmqidbQ61NYgRZgI2HvkOLMHrdLWTcdkt7hZ5ySKUHK
; 9lYWGb4n2qQajspxyLMqz333/f/PGPf5T3YTWS2NRB8ruZAm3ZsmXCag899NDdrF3IdKLpA/4sfAJc
; fKb1mFyoLqtvjNhQtpAsF4xYRoFOR3Q1TjXAZKBDmdcQSib62bOt1fRtrROwAQR1C5lDkbfTJTm81y
; 8rqt0Ai+7L3+VvMDTV3ydSK1qCgRZYVMP9p72KFhhWAzdSslUzy3S3rvFBQ65Mrysd2LQQnMdkhcpx
; IpP5Yrcoz0jPg2P4Da6LSCMAoyzrP//5jxQfEyzRPVWJUmbCatg8On/+fMM0a/z48flntSjR9AF/HM
; V2XCgdlY7taBhYkQ5J1pipAJfNXC5VxDIKdMxR1I3SjYeiQMdndCJgY+KNQQvbebrHYb3O9Ws8N88F
; B0A5LIGVgdIsyryoj1Q3VBd+yq7I3vPewIqE46sHgKbbOwC+7oCb2UNezfn/4PngRqEMEJo7C4NNay
; DpI104GrUMJ9fIZDJ2yzTZrYuRKcFibvb3v/9dXEeeAzqq+hk46B/qIlPVQQIsplAKLodk7o0bN+7e
; gw8+ePtnP/tZAuIpK7akqsfkwlm6kGxep3mvOMn0YrBcqqJmZTtARDVCmOkUkISUNeiirprvZirwnM
; 92t9abA42Vfu7L3zavcnDt4z6vah9ABjds1T1XTnibF+E+HgsltyX1UD/H7G9Z7f938Jw4Z95jPgPj
; hQcTnnOufB6uKEm3sruY7BZlV59//rnUQRKFpIKEc9XrxAOjRCsKYAougPWrX/3qroLrxz/+cVPZSJ
; F09ZhMRml8BZ7WQmpgJK7bWQiWyxR0GB7GSIQM8KlRMmICNNhCDTc8t4sEnsM6e5zI5v6q8iFlWOFt
; 8454G86Km+nMw3rqFppOB7T7GyrlsavJ1W4e1y4Q9zEZ0IKRSJ4zVyWxrNfEd4jWaRVOIcGWD3YLf6
; YFyDAcfaUuJlsiwNZRCWrcQwhkRIErlaQKqMB0mlCkw7LZGz5blisE6DBS8jkYJYYK2HAnk+XqUgFP
; de+OdtPlgARXknwagRWY67gTuk84Ob4OwLWxwezcvF7AGtao34wCWlTYX3OQuFtcD66m5iILAbZ8sh
; vHwlrPP/+8nBvv6f/DahRpoARM+CwcXZwxY0Zx5mGFkFQBFTrvww8/FMPMFGxRgMvGtcwWdGHgYawY
; KMyGe6JgC87rkgEvDL4wAEkr7GqqNvsccO3YtC4SSMk0/Lvh/40CmrqQHA/gGETUJU4WjcwGbLm4kl
; GA4/t6nlwbLiSuJCVa5NUYOOgXWI2lZmF7JGmdU4J6pEiqekxcTAIqNFI26YN8upbZgE5zdMzjNIhC
; Z/MadywqihkEXhzwpWPCKGDFAVkyoOkclIGD5wyMGDJRVlxNLezOBmyFciU5hvP67rvvpCyLSCR5tp
; deesl88803soQG4BH6D9dBZlV2lYP8Pz9x9iRvP6JDAAAAAElFTkSuQmCC
; thumbnail end
;
;

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

; MOST OF GCODES WERE REMOVED TO REDUCE THE SIZE OF THE TESTFILE
M73 P0 R129
; Filament-specific end gcode
G1 E-1 F2100 ; retract
G1 Z95.15 F720 ; Move print head up
G1 X178 Y180 F4200 ; park print head
G4 ; wait
M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
M221 S100 ; reset flow
M84 ; disable motors
M73 P100 R0

; filament used [mm] = 7003.4
; filament used [cm3] = 16.8
; filament used [g] = 21.4
; filament cost = 0.6
; total filament used [g] = 21.4
; total filament cost = 0.6
; estimated printing time (normal mode) = 2h 9m 24s

; avoid_crossing_perimeters = 0
; bed_custom_model =
; bed_custom_texture =
; bed_shape = 0x0,180x0,180x180,0x180
; bed_temperature = 90
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n\n
; between_objects_gcode =
; bottom_fill_pattern = rectilinear
; bottom_solid_layers = 4
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 50
; bridge_flow_ratio = 0.95
; bridge_speed = 30
; brim_width = 0
; clip_multipart_objects = 1
; compatible_printers_condition_cummulative = "printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.4";"printer_model==\"MINI\" and nozzle_diameter[0]!=0.6"
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 1250
; default_filament_profile = "Prusament PLA"
; default_print_profile = 0.15mm QUALITY MINI
; deretract_speed = 40
; disable_fan_first_layers = 3
; dont_support_bridges = 1
; duplicate_distance = 6
; elefant_foot_compensation = 0
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = G1 E-1 F2100 ; retract\n{if layer_z < max_print_height}G1 Z{z_offset+min(layer_z+5, max_print_height)}{endif} F720 ; Move print head up\nG1 X178 Y180 F4200 ; park print head\nG4 ; wait\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\nM221 S100 ; reset flow\nM84 ; disable motors
; ensure_vertical_shell_thickness = 0
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 40
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 35
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.45
; fan_always_on = 1
; fan_below_layer_time = 20
; filament_colour = #FF8000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 27.82
; filament_density = 1.27
; filament_deretract_speed = 25
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 7
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_retract_before_travel = 1
; filament_retract_speed = 40
; filament_settings_id = "Prusa PETG MINI"
; filament_soluble = 0
; filament_toolchange_delay = 0
; filament_type = PETG
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; fill_angle = 45
; fill_density = 0%
; fill_pattern = grid
; first_layer_acceleration = 800
; first_layer_bed_temperature = 85
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.2
; first_layer_speed = 20
; first_layer_temperature = 230
; gap_fill_speed = 40
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = 0
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 1000
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 110
; interface_shells = 0
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.25
; machine_max_acceleration_e = 5000
; machine_max_acceleration_extruding = 1250
; machine_max_acceleration_retracting = 1250
; machine_max_acceleration_x = 1250
; machine_max_acceleration_y = 1250
; machine_max_acceleration_z = 400
; machine_max_feedrate_e = 80
; machine_max_feedrate_x = 180
; machine_max_feedrate_y = 180
; machine_max_feedrate_z = 12
; machine_max_jerk_e = 10
; machine_max_jerk_x = 8
; machine_max_jerk_y = 8
; machine_max_jerk_z = 2
; machine_min_extruding_rate = 0
; machine_min_travel_rate = 0
; max_fan_speed = 50
; max_layer_height = 0.25
; max_print_height = 180
; max_print_speed = 150
; max_volumetric_speed = 0
; min_fan_speed = 30
; min_layer_height = 0.07
; min_print_speed = 15
; min_skirt_length = 4
; notes =
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{layer_height}mm_{filament_type[0]}_{printer_model}_{print_time}.gcode
; overhangs = 0
; parking_pos_retraction = 92
; perimeter_acceleration = 800
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_speed = 55
; perimeters = 1
; post_process =
; print_host =
; print_settings_id = 0.25mm DRAFT MINI
; printer_model = MINI
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MINI\n
; printer_settings_id = Original Prusa MINI
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor =
; printhost_apikey =
; printhost_cafile =
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 1.5
; retract_before_wipe = 70%
; retract_layer_change = 0
; retract_length = 3.2
; retract_length_toolchange = 4
; retract_lift = 0.2
; retract_lift_above = 0
; retract_lift_below = 179
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 70
; seam_position = nearest
; serial_port =
; serial_speed = 250000
; silent_mode = 0
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 2
; skirt_height = 3
; skirts = 1
; slice_closing_radius = 0.049
; slowdown_below_layer_time = 20
; small_perimeter_speed = 25
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 100
; spiral_vase = 1
; standby_temperature_delta = -5
; start_filament_gcode = "M900 K{if nozzle_diameter[0]==0.6}0.12{else}0.2{endif} ; Filament gcode"
; start_gcode = G90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S170 ; set extruder temp for bed leveling\nM140 S[first_layer_bed_temperature] ; set bed temp\nM109 R170 ; wait for bed leveling temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nG28 ; home all without mesh bed level\nG29 ; mesh bed leveling \nM104 S[first_layer_temperature] ; set extruder temp\nG92 E0.0\nG1 Y-2.0 X179 F2400\nG1 Z3 F720\nM109 S[first_layer_temperature] ; wait for extruder temp\n\n; intro line\nG1 X170 F1000\nG1 Z0.2 F720\nG1 X110.0 E8.0 F900\nG1 X40.0 E10.0 F700\nG92 E0.0\n\nM221 S95 ; set flow
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_buildplate_only = 0
; support_material_contact_distance = 0.1
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 40
; support_material_synchronize_layers = 0
; support_material_threshold = 55
; support_material_with_sheath = 0
; support_material_xy_spacing = 60%
; temperature = 240
; thin_walls = 0
; threads = 8
; thumbnails = 16x16,220x124
; toolchange_gcode =
; top_fill_pattern = rectilinear
; top_infill_extrusion_width = 0.4
; top_solid_infill_speed = 45
; top_solid_layers = 0
; travel_speed = 150
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
